# Generated by Django 4.2.4 on 2023-08-17 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookItems', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='image',
            field=models.CharField(default='', max_length=150, null=True),
        ),
    ]
